FROM python:3.9

WORKDIR /app

RUN apt update && apt install -y python3-pip ffmpeg

COPY requirements.display.txt requirements.txt

RUN pip3 install --no-cache-dir -r requirements.txt

COPY display.py .

CMD ["python3", "display.py"]


